spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/binderua2
    username: binder_ua
    password: kd$423DFG
  jpa:
    show-sql: true

logging:
  level:
    root: INFO
    com.timetracker: DEBUG
